apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: mongo-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongodb-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: mongo-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongodb-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: mongo-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongodb-2
