apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-sc
  resources:
    requests:
      storage: 10Gi
