apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-pod-access
  namespace: prod
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: prod
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
