apiVersion: v1
kind: Pod
metadata:
  name: nginx-multi-container-pod
  namespace: prod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

    - name: sidecar-logger
      image: busybox
      command: ["sh", "-c", "while true; do echo Logging...; sleep 10; done"]
